services:
    payroll.service.calendar:
        class: PayrollBundle\Service\CalendarService
    payroll.service.payday:
        class: PayrollBundle\Service\PaydayService
    payroll.service.payroll:
        class: PayrollBundle\Service\PayrollService
        arguments: ['@payroll.service.calendar', '@payroll.service.payday']
